- name: copy nagios vhost
  become: true
  template: >
    src=nagios.vhost.j2
    dest=/etc/apache2/sites-available/nagios.conf
    owner=root
    group=root
    mode=640
  when: not (legacy | default(false))

- name: enable nagios vhost
  become: true
  command: "a2ensite nagios"
