- name: Install config files
  become: true
  notify: restart nagios
  template: >
    src={{item.src}}
    dest={{nagios_object_dir}}/{{item.dest}}
    owner={{nagios_user}}
    group={{nagios_group}}
  with_items:
    - { src: hosts.cfg.j2, dest: hosts.cfg }
    - { src: hostgroups.cfg.j2, dest: hostgroups.cfg }
    - { src: services.cfg.j2, dest: services.cfg }
    - { src: commands.cfg.j2, dest: additional_commands.cfg }
    - { src: contacts.cfg.j2, dest: contacts.cfg }

- name: load hosts.cfg
  become: true
  notify: restart nagios
  lineinfile: >
    dest=/usr/local/nagios/etc/nagios.cfg
    line="cfg_file=/usr/local/nagios/etc/objects/hosts.cfg"
    regexp="cfg_file\=/usr/local/nagios/etc/objects/hosts\.cfg"

- name: load hostgroups.cfg
  become: true
  notify: restart nagios
  lineinfile: >
    dest=/usr/local/nagios/etc/nagios.cfg
    line="cfg_file=/usr/local/nagios/etc/objects/hostgroups.cfg"
    regexp="cfg_file\=/usr/local/nagios/etc/objects/hostgroups\.cfg"

- name: load contacts.cfg
  become: true
  notify: restart nagios
  lineinfile: >
    dest=/usr/local/nagios/etc/nagios.cfg
    line="cfg_file=/usr/local/nagios/etc/objects/contacts.cfg"
    regexp="cfg_file\=/usr/local/nagios/etc/objects/contacts\.cfg"

- name: load additional_commands.cfg
  become: true
  notify: restart nagios
  lineinfile: >
    dest=/usr/local/nagios/etc/nagios.cfg
    line="cfg_file=/usr/local/nagios/etc/objects/additional_commands.cfg"
    regexp="cfg_file\=/usr/local/nagios/etc/objects/additional_commands\.cfg"

- name: load services.cfg
  become: true
  notify: restart nagios
  lineinfile: >
    dest=/usr/local/nagios/etc/nagios.cfg
    line="cfg_file=/usr/local/nagios/etc/objects/services.cfg"
    regexp="cfg_file\=/usr/local/nagios/etc/objects/services\.cfg"


- name: setup cfg_dir
  become: true
  notify: restart nagios
  lineinfile: >
    dest={{nagios_base_dir}}/etc/nagios.cfg
    line="cfg_dir={{nagios_object_dir}}"
    regexp="^cfg_dir={{nagios_object_dir}}"
  when: nagios_cfg_dir_enabled == true

# PagerDuty
- name: configure pagerduty
  tasks:
  include: pagerduty.yml
  when: nagios_enable_pagerduty_notifications

# SES
- name: configure amazon ses
  tasks:
  include: ses.yml
  when: nagios_enable_ses_notifications

# Slack
- name: configure slack
  tasks:
  include: slack.yml
  when: nagios_enable_slack_notifications

# Apache VHOST for Nagios
- name: configure apache nagios vhost
  tasks: 
  include: apache.yml
  notify: restart nagios
  notify: restart apache

- include: ssh_keys.yml
